name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' 

      - name: Install dependencies
        run: |
          npm install
          npm install ts-node typescript @cross/test @std/assert

      - name: Run tests
        run: |
          find . -type f -name "*.test.ts" | while read -r file; do
            echo "Running tests in $file"
            npx ts-node "$file"
          done
